### ISSUE TITLE
Set focus to next editBox

### ISSUE THREAD

**Issue by masterlsc** [nostek/UnityNativeEditBox#1]
When Return button type is set to next, it dosent set focus to net EditBox. This is tested on Android phone

**Comment by nostek** [comment]
This is expected behaviour, the "focus on next" functionality should be controlled in Unity with OnSubmit.

**Comment by masterlsc** [comment]
Ok thanks, and very cool implementation really great work

**Comment by nostek** [comment]
Thanks! :)
