### ISSUE TITLE
Close Keyboard on Return?

### ISSUE THREAD

**Issue by liam-bozward** [nostek/UnityNativeEditBox#5]
Hello,

Firstly thanks for providing this; and apologies if I've managed to miss the workaround for this!

I noticed you included the option to change the "Return Button Type" however the button doesn't seem to work whilst in use, so I have to tap outside of the keyboard for it to close. Any suggestions around this? 

I'm using Unity 2017.2.1f1 If that makes any difference, I did attempt to use a plugin similar to this in which the option to assign an event to the "Return" was provided and worked however this one didn't fix the performance bug I was encountering (https://github.com/YousicianGit/UnityNativeEdit) (https://issuetracker.unity3d.com/issues/android-application-lag-terribly-when-returning-from-input-field-slash-soft-keyboard-entry-on-android). This plugin however works great just the little issue I noted above.

Many thanks!

**Comment by nostek** [comment]
Hi!
Strange! Is this on Android or iOS or both?
Can't look at this today I'm afraid, but can tomorrow (2017-12-13)

-Simon

**Comment by liam-bozward** [comment]
Hi!

Android, I don't think I'll need to use the plugin for iOS as the performance issue I've encountered is just on Android from what I can see. And thats okay, appreciate the help! 👍

**Comment by nostek** [comment]
Hi!

I misread the question yesterday :)
The return button does not close the keyboard automatically.
Use DestroyNative() in the callback from the 'OnSubmit' event.

Hope that helps!

**Comment by liam-bozward** [comment]
Hi,

Think I got it working, added it to the "Android_SubmitPressed" or have I gone the wrong way with it? Sorry for being a bit dumb with this!

Thanks!

**Comment by nostek** [comment]
That works :)
